"""Stablecoin route matrix for Meridian's payment economy."""

from __future__ import annotations

from .types import BalanceDomain, Protocol, RouteSpec, SettlementPrimitive


ROUTE_MATRIX: list[RouteSpec] = [
    RouteSpec(
        route_id="base_direct_usdc",
        source_domain=BalanceDomain.BASE_USDC,
        target_domain=BalanceDomain.BASE_USDC,
        primitive=SettlementPrimitive.DIRECT_SAME_DOMAIN,
        supported_protocols=[Protocol.X402, Protocol.AP2, Protocol.ATXP],
        fee_bps=3,
        fixed_fee_cents=1,
        latency_ms=180,
        capacity_cents_per_round=2_500_000,
        base_fail_prob=0.01,
    ),
    RouteSpec(
        route_id="solana_direct_usdc",
        source_domain=BalanceDomain.SOLANA_USDC,
        target_domain=BalanceDomain.SOLANA_USDC,
        primitive=SettlementPrimitive.DIRECT_SAME_DOMAIN,
        supported_protocols=[Protocol.X402, Protocol.AP2, Protocol.ATXP],
        fee_bps=4,
        fixed_fee_cents=1,
        latency_ms=220,
        capacity_cents_per_round=2_000_000,
        base_fail_prob=0.012,
    ),
    RouteSpec(
        route_id="tempo_direct_session",
        source_domain=BalanceDomain.TEMPO_USD,
        target_domain=BalanceDomain.TEMPO_USD,
        primitive=SettlementPrimitive.TEMPO_SESSION,
        supported_protocols=[Protocol.MPP],
        fee_bps=7,
        fixed_fee_cents=1,
        latency_ms=420,
        capacity_cents_per_round=1_800_000,
        base_fail_prob=0.015,
    ),
    RouteSpec(
        route_id="gateway_batch_settle",
        source_domain=BalanceDomain.BASE_USDC,
        target_domain=BalanceDomain.GATEWAY_UNIFIED_USDC,
        primitive=SettlementPrimitive.BATCHED_NANOPAYMENT,
        supported_protocols=[Protocol.X402],
        fee_bps=1,
        fixed_fee_cents=0,
        latency_ms=60,
        capacity_cents_per_round=3_500_000,
        base_fail_prob=0.005,
    ),
    RouteSpec(
        route_id="stripe_internal_sink",
        source_domain=BalanceDomain.STRIPE_INTERNAL_USD,
        target_domain=BalanceDomain.STRIPE_INTERNAL_USD,
        primitive=SettlementPrimitive.STRIPE_INTERNAL_CHECKOUT,
        supported_protocols=[Protocol.ACP, Protocol.MPP],
        fee_bps=10,
        fixed_fee_cents=5,
        latency_ms=900,
        capacity_cents_per_round=4_000_000,
        base_fail_prob=0.02,
    ),
    RouteSpec(
        route_id="cctp_base_to_solana",
        source_domain=BalanceDomain.BASE_USDC,
        target_domain=BalanceDomain.SOLANA_USDC,
        primitive=SettlementPrimitive.CCTP_TRANSFER,
        supported_protocols=[Protocol.AP2],
        fee_bps=8,
        fixed_fee_cents=4,
        latency_ms=1450,
        capacity_cents_per_round=1_500_000,
        base_fail_prob=0.025,
    ),
    RouteSpec(
        route_id="cctp_solana_to_base",
        source_domain=BalanceDomain.SOLANA_USDC,
        target_domain=BalanceDomain.BASE_USDC,
        primitive=SettlementPrimitive.CCTP_TRANSFER,
        supported_protocols=[Protocol.AP2],
        fee_bps=8,
        fixed_fee_cents=4,
        latency_ms=1450,
        capacity_cents_per_round=1_500_000,
        base_fail_prob=0.025,
    ),
    RouteSpec(
        route_id="lifi_base_to_stripe_sink",
        source_domain=BalanceDomain.BASE_USDC,
        target_domain=BalanceDomain.STRIPE_INTERNAL_USD,
        primitive=SettlementPrimitive.LIFI_ROUTED,
        supported_protocols=[Protocol.ACP, Protocol.ATXP],
        fee_bps=18,
        fixed_fee_cents=7,
        latency_ms=1800,
        capacity_cents_per_round=1_200_000,
        base_fail_prob=0.045,
    ),
    RouteSpec(
        route_id="lifi_base_to_gateway",
        source_domain=BalanceDomain.BASE_USDC,
        target_domain=BalanceDomain.GATEWAY_UNIFIED_USDC,
        primitive=SettlementPrimitive.LIFI_ROUTED,
        supported_protocols=[Protocol.AP2, Protocol.ATXP],
        fee_bps=13,
        fixed_fee_cents=5,
        latency_ms=1300,
        capacity_cents_per_round=1_400_000,
        base_fail_prob=0.03,
    ),
    RouteSpec(
        route_id="lifi_solana_to_gateway",
        source_domain=BalanceDomain.SOLANA_USDC,
        target_domain=BalanceDomain.GATEWAY_UNIFIED_USDC,
        primitive=SettlementPrimitive.LIFI_ROUTED,
        supported_protocols=[Protocol.AP2, Protocol.ATXP],
        fee_bps=15,
        fixed_fee_cents=6,
        latency_ms=1500,
        capacity_cents_per_round=1_250_000,
        base_fail_prob=0.034,
    ),
    RouteSpec(
        route_id="lifi_tempo_to_base",
        source_domain=BalanceDomain.TEMPO_USD,
        target_domain=BalanceDomain.BASE_USDC,
        primitive=SettlementPrimitive.LIFI_ROUTED,
        supported_protocols=[Protocol.ATXP],
        fee_bps=20,
        fixed_fee_cents=8,
        latency_ms=2100,
        capacity_cents_per_round=900_000,
        base_fail_prob=0.055,
    ),
]


def routes_for_protocol(protocol: Protocol) -> list[RouteSpec]:
    return [route for route in ROUTE_MATRIX if protocol in route.supported_protocols]
